/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentDecideRouteImport } from './routes/api/public/agent/decide'
import { Route as ApiPublicAgentPlanRouteImport } from './routes/api/public/agent/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentDecideRoute = ApiPublicAgentDecideRouteImport.update({
  id: '/api/public/agent/decide',
  path: '/api/public/agent/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPlanRoute = ApiPublicAgentPlanRouteImport.update({
  id: '/api/public/agent/plan',
  path: '/api/public/agent/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/agent/decide': typeof ApiPublicAgentDecideRoute
  '/api/public/agent/plan': typeof ApiPublicAgentPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/agent/decide': typeof ApiPublicAgentDecideRoute
  '/api/public/agent/plan': typeof ApiPublicAgentPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/agent/decide': typeof ApiPublicAgentDecideRoute
  '/api/public/agent/plan': typeof ApiPublicAgentPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/agent/decide' | '/api/public/agent/plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/agent/decide' | '/api/public/agent/plan'
  id: '__root__' | '/' | '/api/public/agent/decide' | '/api/public/agent/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAgentDecideRoute: typeof ApiPublicAgentDecideRoute
  ApiPublicAgentPlanRoute: typeof ApiPublicAgentPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/decide': {
      id: '/api/public/agent/decide'
      path: '/api/public/agent/decide'
      fullPath: '/api/public/agent/decide'
      preLoaderRoute: typeof ApiPublicAgentDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/plan': {
      id: '/api/public/agent/plan'
      path: '/api/public/agent/plan'
      fullPath: '/api/public/agent/plan'
      preLoaderRoute: typeof ApiPublicAgentPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAgentDecideRoute: ApiPublicAgentDecideRoute,
  ApiPublicAgentPlanRoute: ApiPublicAgentPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
